# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hcb
  username: postgres
  password: postgres
  host: db

test:
  <<: *default
  database: hcb_test
  username: postgres
  password: postgres
  host: db

production:
  <<: *default
  database: hcb_production
  username: postgres
  password: postgres
  host: db
